# Generated by Django 4.2.4 on 2023-08-23 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='groups', to='main.interest'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='attending_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='groups', to='main.photo'),
        ),
    ]
