# Generated by Django 4.2.3 on 2023-09-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
