# Generated by Django 4.2.4 on 2023-09-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_location_lat_group_location_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.CharField(max_length=256),
        ),
    ]
