# Generated by Django 4.2.4 on 2023-08-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('event', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='events', to='main.interest'),
        ),
        migrations.AddField(
            model_name='event',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='event', to='main.photo'),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='group.group'),
        ),
    ]
