# Generated by Django 4.2.3 on 2023-09-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_bio_user_interests_user_location_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
